FROM oven/bun:1.2.18-slim
WORKDIR /
RUN bun add --no-save playwright-core@1.52.0
# https://github.com/oven-sh/bun/issues/9911
RUN sed -i \
's;require("./utilsBundleImpl").ws;("Bun" in globalThis) ? require("ws") : &;' \
node_modules/playwright-core/lib/utilsBundle.js
